### ISSUE TITLE
Python Websocket Subscription not Printing

### ISSUE THREAD

**Issue by daveebbelaar** [bitvavo/python-bitvavo-api#10]
I followed the API documentation to access /subscribeTicker24h through Python.

However, the code doesn't show any output. Am I missing something?

The following code results in an endless loop with no output:

`from python_bitvavo_api.bitvavo import Bitvavo`

`def callback(response):`
  `print("Callback:", json.dumps(response, indent=2))`

`def errorCallback(error):`
  `print("Error callback:", json.dumps(error, indent=2))`

`bitvavo = Bitvavo()`
`websocket = bitvavo.newWebsocket()`
`websocket.setErrorCallback(errorCallback)`

`websocket.subscriptionTicker24h('BTC-EUR', callback)`

**Comment by rroumenov** [comment]
Here the same issue. But I have to say that I have tested Subscriptions a week or 2 ago, and was successful. Dont know what happend today but seems like cannot connect to servers. Maybe they are offline or this framework needs some kind of update.

**Comment by rroumenov** [comment]
@daveebbelaar 
My man, I found whats the problem. Nothing about upgrading and down servers as I first suspect from my lack of knowledge.
The problem is the websocket-client framework. From the last version 0.58.0, change was made in `websocket/_app.py`. You can see in the following issue already opened in websockets github:
#https://github.com/websocket-client/websocket-client/issues/669#issue-828897810

Seems to be solved Issue, because I found post from 2018 which talks about it here:
#https://github.com/joliveros/bitmex-websocket/issues/14#issue-379711208

but somehow they pull some kind of change which broke it again.

I just edited `_app.py` by myself and now it runs like a charm, but you can also download the 0.57.0 with PIP3 where, if I remember well, this error not exists.

Sorry to Bitvavo to suspect about fallen server :P

Regards!
